name: Deploy Discord Bot to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "22"

            - name: Install dependencies
              run: npm ci

            - name: Deploy to VPS via SSH
              uses: appleboy/scp-action@v0.1.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_KEY }}
                  source: "."
                  target: "/home/${{ secrets.VPS_USER }}/discord-bot"

            - name: Upload .env
              run: |
                  echo "${{ secrets.ENV_FILE }}" > .env
              shell: bash

            - name: Upload .env to VPS
              uses: appleboy/scp-action@v0.1.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_KEY }}
                  source: ".env"
                  target: "/home/${{ secrets.VPS_USER }}/discord-bot"

            - name: SSH Remote Commands
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_KEY }}
                  script: |
                      cd ~/discord-bot
                      export NVM_DIR="$HOME/.nvm"
                      source "$NVM_DIR/nvm.sh"
                      npm install
                      npm run register-commands
                      pm2 restart bot || pm2 start npm --name bot -- run start
                      pm2 save
